# Generated by Django 4.2 on 2023-07-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertificationcode',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vertificationcode',
            name='sTime',
            field=models.IntegerField(default=0),
        ),
    ]
