# Generated by Django 4.1.4 on 2023-07-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_vertificationcode_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VertificationCodePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('sTime', models.IntegerField()),
                ('code', models.IntegerField()),
            ],
        ),
    ]
