# Generated by Django 4.2.3 on 2023-07-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_vertificationcodephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertificationcodephone',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vertificationcodephone',
            name='sTime',
            field=models.IntegerField(default=0),
        ),
    ]
