# Generated by Django 4.2 on 2023-05-11 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_title', models.CharField(max_length=16)),
                ('participants', models.ManyToManyField(to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='MSG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=256)),
                ('date', models.TimeField(default=django.utils.timezone.now)),
                ('roomRelated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
                ('userRelated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
