# Generated by Django 4.2 on 2023-05-11 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
