# Generated by Django 4.2 on 2023-05-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='start_time',
            field=models.CharField(default='None', max_length=240),
        ),
    ]
