# Generated by Django 4.2 on 2023-06-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_plan_price_student_plans'),
        ('room', '0003_alter_room_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهار شنبه', 'چهار شنبه'), ('پنج شنبه', 'پنج شنبه'), ('جمعه', 'جمعه')], max_length=48)),
                ('date', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('دهم', 'دهم'), ('یازدهم', 'یازدهم'), ('دوازدهم', 'دوازدهم')], max_length=50)),
                ('time', models.CharField(max_length=100)),
                ('toDo', models.CharField(max_length=256)),
                ('ScheduleRelated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.schedule')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='room',
            name='start_time',
        ),
        migrations.AddField(
            model_name='room',
            name='enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='plan',
            field=models.ManyToManyField(to='home.plan'),
        ),
        migrations.DeleteModel(
            name='MSG',
        ),
    ]
