# Generated by Django 4.2 on 2023-06-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_schedule_scheduleitem_remove_room_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
    ]
