# Generated by Django 4.2 on 2023-06-10 18:16

from django.db import migrations, models
import room.models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_remove_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.CharField(default=room.models.Schedule.get_now_time, max_length=48),
        ),
    ]
