# Generated by Django 4.2 on 2023-06-10 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ScheduleRelated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.schedule'),
        ),
    ]
