# Generated by Django 4.1.4 on 2023-04-03 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_student_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
