# Generated by Django 4.2 on 2023-05-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Solution',
        ),
    ]
