# Generated by Django 4.2 on 2023-05-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_ticket_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='awnsered',
        ),
        migrations.AddField(
            model_name='solution',
            name='position',
            field=models.CharField(default='باز', max_length=10),
        ),
    ]
