# Generated by Django 4.2 on 2023-05-27 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_solution_awnsered_solution_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='create_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solution',
            name='content',
            field=models.CharField(max_length=480),
        ),
        migrations.AlterField(
            model_name='solution',
            name='moredata',
            field=models.ImageField(blank=True, null=True, upload_to='tickets-data'),
        ),
    ]
