# Generated by Django 4.2 on 2023-05-27 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_solution_create_time_alter_solution_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
