# Generated by Django 4.2 on 2023-05-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_solution_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
