# Generated by Django 4.2 on 2023-05-27 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_solution_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='moredata',
            field=models.ImageField(blank=True, null=True, upload_to='probloms_pics'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=480)),
                ('file', models.FileField(blank=True, null=True, upload_to='probloms_files')),
                ('time', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('problom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.solution')),
            ],
        ),
    ]
