# Generated by Django 4.2 on 2023-05-28 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_solution_moredata_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
