# Generated by Django 4.2 on 2023-05-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_solution_publish_alter_answer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='subject',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
