# Generated by Django 4.2 on 2023-05-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_answer_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='grade',
            field=models.CharField(choices=[('دهم', 'دهم'), ('یازدهم', 'یازدهم'), ('دوازدهم', 'دوازدهم')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='solution',
            name='unit',
            field=models.CharField(choices=[('اول', 'فصل اول'), ('دوم', 'فصل دوم'), ('سوم', 'فصل سوم'), ('چهارم', 'فصل چهارم')], default='', max_length=16),
        ),
    ]
