# Generated by Django 4.2 on 2023-05-28 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_solution_grade_solution_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='problom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.solution'),
        ),
    ]
