# Generated by Django 4.2 on 2023-05-28 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_answer_problom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='likes',
        ),
        migrations.CreateModel(
            name='SolutionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.solution')),
            ],
        ),
    ]
