# Generated by Django 4.2 on 2023-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_feature_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_users',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, max_length=12000),
        ),
    ]
