# Generated by Django 4.2 on 2023-06-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_plan_max_users_alter_feature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_users',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
