# Generated by Django 4.2 on 2023-06-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_plan_max_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.CharField(default='0', max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='plans',
            field=models.ManyToManyField(to='home.plan'),
        ),
    ]
