# Generated by Django 4.1.4 on 2023-07-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_plan_price_student_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='max_users',
        ),
    ]
