# Generated by Django 4.2.3 on 2023-08-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_student_full_name_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='price',
            new_name='Globalprice',
        ),
        migrations.AddField(
            model_name='plan',
            name='Studentprice',
            field=models.CharField(default='0', max_length=120),
        ),
    ]
