# Generated by Django 4.1.4 on 2023-04-05 23:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.png', force_format='JPEG', keep_meta=True, quality=100, scale=1, size=[1920, 1080], upload_to='video_thumbnail'),
        ),
    ]
