# Generated by Django 4.1.4 on 2023-04-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Thumbnail',
            field=models.ImageField(default='default.png', upload_to='video_thumbnail'),
        ),
    ]
