# Generated by Django 4.1.4 on 2023-04-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Unit',
            field=models.CharField(choices=[('', ''), ('اول', 'فصل اول'), ('دوم', 'فصل دوم'), ('سوم', 'فصل سوم'), ('فصل', 'فصل چهارم')], default='', max_length=16),
        ),
    ]
