# Generated by Django 4.2 on 2023-05-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Unit',
            field=models.CharField(choices=[('', ''), ('اول', 'فصل اول'), ('دوم', 'فصل دوم'), ('سوم', 'فصل سوم'), ('چهارم', 'فصل چهارم')], default='', max_length=16),
        ),
    ]
