# Generated by Django 4.2 on 2023-07-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_alter_video_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='File',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
