# Generated by Django 4.2.3 on 2023-07-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_remove_video_file_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Type',
            field=models.CharField(choices=[('دانش آموزان', 'حل تست به همراهی دانش آموزان'), ('نکته تست', 'نکته تست'), ('درسنامه', 'درسنامه')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='video',
            name='Unit',
            field=models.CharField(choices=[('اول', 'فصل اول'), ('دوم', 'فصل دوم'), ('سوم', 'فصل سوم'), ('چهارم', 'فصل چهارم')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='video',
            name='grade',
            field=models.CharField(choices=[('دهم', 'دهم'), ('یازدهم', 'یازدهم'), ('دوازدهم', 'دوازدهم')], default='', max_length=16),
        ),
    ]
