# Generated by Django 4.2.3 on 2023-08-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_video_type_alter_video_unit_alter_video_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='video_thumbnail'),
        ),
    ]
