# Generated by Django 4.2 on 2023-07-13 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0020_plan_price_student_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('grade', models.CharField(choices=[('دهم', 'دهم'), ('یازدهم', 'یازدهم'), ('دوازدهم', 'دوازدهم'), ('فارغ التحصیل', 'فارغ التحصیل')], max_length=16, null=True)),
                ('unit', models.CharField(choices=[('اول', 'فصل اول'), ('دوم', 'فصل دوم'), ('سوم', 'فصل سوم'), ('چهارم', 'فصل چهارم')], max_length=16, null=True)),
                ('time', models.IntegerField(default=40)),
                ('date', models.CharField(default='', max_length=48)),
                ('startTime', models.TimeField(default=django.utils.timezone.now)),
                ('endTime', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='None', max_length=16)),
                ('Stime', models.CharField(blank=True, default='', max_length=254)),
                ('plans', models.ManyToManyField(to='home.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.ImageField(default='default.png', upload_to='questions_pics')),
                ('Answer', models.CharField(choices=[('1', 'گزینه اول'), ('2', 'گزینه دوم'), ('3', 'گزینه سوم'), ('4', 'گزینه چهارم')], default=0, max_length=1)),
                ('Grade', models.CharField(choices=[('', ''), ('دهم', 'دهم'), ('یازدهم', 'یازدهم'), ('دوازدهم', 'دوازدهم'), ('فارغ التحصیل', 'فارغ التحصیل')], default='', max_length=16)),
                ('Unit', models.CharField(choices=[('', ''), ('اول', 'فصل اول'), ('دوم', 'فصل دوم'), ('سوم', 'فصل سوم'), ('چهارم', 'فصل چهارم')], default='', max_length=16)),
                ('difficulty', models.CharField(default='50,1', max_length=48)),
                ('date_submited', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('voting', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='virtualExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField(default=20)),
                ('filters', models.CharField(max_length=480)),
                ('status', models.CharField(max_length=24)),
                ('difficulty', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('questions', models.ManyToManyField(to='exam.question')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answers', models.CharField(max_length=320)),
                ('timeSpended', models.CharField(max_length=128, null=True)),
                ('percent', models.FloatField()),
                ('wrongs', models.CharField(max_length=128)),
                ('corrects', models.CharField(max_length=128)),
                ('notAnswered', models.CharField(max_length=128, null=True)),
                ('dateSubmited', models.DateTimeField(default=django.utils.timezone.now)),
                ('wrongs_link', models.CharField(max_length=400, null=True)),
                ('corrects_link', models.CharField(max_length=400, null=True)),
                ('notAnswered_link', models.CharField(max_length=400, null=True)),
                ('Exam_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.FileField(default='default.png', upload_to='question-solution')),
                ('date_submited', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=480)),
                ('questionRelated', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=2000)),
                ('startTime', models.CharField(default='None', max_length=128)),
                ('Exam_related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('student_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
