# Generated by Django 4.2 on 2023-07-14 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0002_virtualexam_keys_virtualexam_studentrelated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualexam',
            name='keys',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='virtualexam',
            name='studentRelated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
