# Generated by Django 4.1.4 on 2023-07-18 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0003_alter_virtualexam_keys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='voting',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
