# Generated by Django 4.2.3 on 2023-10-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_question_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exampdf',
            field=models.FileField(default='', upload_to='examPDFS'),
        ),
    ]
